services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4200:80"
    networks:
      - backend

networks:
  backend:
    external: true
